version: '3.7'
services:
  prometheus:
    tty: true
    environment:
      TZ: "Asia/Shanghai"
    image: prom/prometheus
    container_name: prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    restart: always
    ports:
      - "10001:9090"
    volumes:
      - /Users/snail/IdeaProjects/Kitematic/promethous/promethous.yml:/etc/prometheus/prometheus.yml